# Generated by Django 2.0.7 on 2018-07-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectscent',
            name='scent',
            field=models.CharField(max_length=100),
        ),
    ]
